// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_bYlCr8dVPRYBxszpDryR9m00V1EyQw4',
    appId: '1:802873063793:web:76be835f2ae77026bd9ed0',
    messagingSenderId: '802873063793',
    projectId: 'transaction-app-22461',
    authDomain: 'transaction-app-22461.firebaseapp.com',
    storageBucket: 'transaction-app-22461.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpDmvX_CUb0T--eFqXZcGvHVPKIb7y7_A',
    appId: '1:802873063793:android:76f9e9cd8b263484bd9ed0',
    messagingSenderId: '802873063793',
    projectId: 'transaction-app-22461',
    storageBucket: 'transaction-app-22461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARe7rdzgTlP-24VgItIHnRhaD2A8TF-J4',
    appId: '1:802873063793:ios:3105cab6f0154869bd9ed0',
    messagingSenderId: '802873063793',
    projectId: 'transaction-app-22461',
    storageBucket: 'transaction-app-22461.appspot.com',
    iosBundleId: 'com.example.transactionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARe7rdzgTlP-24VgItIHnRhaD2A8TF-J4',
    appId: '1:802873063793:ios:3105cab6f0154869bd9ed0',
    messagingSenderId: '802873063793',
    projectId: 'transaction-app-22461',
    storageBucket: 'transaction-app-22461.appspot.com',
    iosBundleId: 'com.example.transactionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_bYlCr8dVPRYBxszpDryR9m00V1EyQw4',
    appId: '1:802873063793:web:37c2219b72106317bd9ed0',
    messagingSenderId: '802873063793',
    projectId: 'transaction-app-22461',
    authDomain: 'transaction-app-22461.firebaseapp.com',
    storageBucket: 'transaction-app-22461.appspot.com',
  );
}
